Handle arm64 image

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -26,56 +26,56 @@ jobs:
 
       - name: Build and Push Docker Image
         run: |
-          docker build . \
+          docker buildx build . \
+            --platform linux/amd64,linux/arm64 \
             --tag ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }} \
             --build-arg API_URL=${{ secrets.API_URL }} \
             --build-arg DB_HOST=${{ secrets.DB_HOST }} \
-            --build-arg DB_PASS=${{ secrets.DB_PASS }}
-          
-          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
+            --build-arg DB_PASS=${{ secrets.DB_PASS }} \
+            --push
 
-  deploy:
-    needs: build_and_publish
-    name: Deploy Docker Image to AWS
-    runs-on: ubuntu-latest
+  # deploy:
+  #   needs: build_and_publish
+  #   name: Deploy Docker Image to AWS
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Create SSH Directory and Install Key
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/aws_key.pem
-          chmod 600 ~/.ssh/aws_key.pem
+  #   steps:
+  #     - name: Create SSH Directory and Install Key
+  #       run: |
+  #         mkdir -p ~/.ssh
+  #         echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/aws_key.pem
+  #         chmod 600 ~/.ssh/aws_key.pem
 
-      - name: Add AWS Host to Known Hosts
-        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+  #     - name: Add AWS Host to Known Hosts
+  #       run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
 
-      - name: Deploy to AWS Server
-        run: |
-          ssh -i ~/.ssh/aws_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
-            set -e  # Stop on first error
-            echo "*** Logging into Docker Registry ***"
-            echo "${{ secrets.PAT }}" | docker login ${{ env.DOCKER_REGISTRY }} -u ${{ github.actor }} --password-stdin
-          
-            echo "*** Pulling the latest Docker image ***"
-            docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
-          
-            echo "*** Checking if the target directory exists ***"
-            if [ ! -d "${{ secrets.WORK_DIR }}" ]; then
-              echo "Error: Directory ${{ secrets.WORK_DIR }} does not exist. Deployment aborted." >&2
-              exit 1
-            fi
-          
-            echo "*** Changing to target directory ***"
-            cd ${{ secrets.WORK_DIR }}
-          
-            echo "*** Running Docker Compose ***"
-            docker compose pull && docker compose up -d
-          
-            echo "*** Removing unused Docker images ***"
-            docker image prune -af
-          
-            echo "*** Deployment complete ***"
-          EOF
+  #     - name: Deploy to AWS Server
+  #       run: |
+  #         ssh -i ~/.ssh/aws_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
+  #           set -e  # Stop on first error
+  #           echo "*** Logging into Docker Registry ***"
+  #           echo "${{ secrets.PAT }}" | docker login ${{ env.DOCKER_REGISTRY }} -u ${{ github.actor }} --password-stdin
+  #
+  #           echo "*** Pulling the latest Docker image ***"
+  #           docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
+  #
+  #           echo "*** Checking if the target directory exists ***"
+  #           if [ ! -d "${{ secrets.WORK_DIR }}" ]; then
+  #             echo "Error: Directory ${{ secrets.WORK_DIR }} does not exist. Deployment aborted." >&2
+  #             exit 1
+  #           fi
+  #
+  #           echo "*** Changing to target directory ***"
+  #           cd ${{ secrets.WORK_DIR }}
+  #
+  #           echo "*** Running Docker Compose ***"
+  #           docker compose pull && docker compose up -d
+  #
+  #           echo "*** Removing unused Docker images ***"
+  #           docker image prune -af
+  #
+  #           echo "*** Deployment complete ***"
+  #         EOF
 
-      - name: Clean Up SSH Key
-        run: rm -f ~/.ssh/aws_key.pem
+  #     - name: Clean Up SSH Key
+  #       run: rm -f ~/.ssh/aws_key.pem
